In [41]:
import struct
import pandas as pd

In [42]:
sst_file = 'SBBX.ERSSTv5'

with open(sst_file, 'rb') as binary_file:
    binary_data = binary_file.read()
    
print(binary_data[:100])

b"\x00\x00\x00p\x00\x00\x06\xc0\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x06\xc0\x00\x00\x06\xc8\x00\x00\x07X\x00\x00'\x0f\xff\xff\xd8\xf1Monthly Sea Surface Temperature anom (C) ERSSTv5 01/1880 - 07/20"

In [45]:
# Define the dimensions of your grid (e.g., 360 longitudes, 180 latitudes)
num_longitudes = 360
num_latitudes = 180

# Initialize an empty list to store the data
data = []

# Iterate over the binary data to unpack and organize it
for i in range(num_longitudes):
    for j in range(num_latitudes):
        # Calculate the starting position for each grid point in the binary data
        start_position = 4 * (i + num_longitudes * j)  # Assuming 4-byte (32-bit) float

        # Extract the floating-point value from the binary data
        value = struct.unpack('>f', binary_data[start_position : start_position + 4])[0]

        # Append the value along with longitude and latitude to the data list
        data.append([i, j, value])

# Create a Pandas DataFrame from the organized data
df = pd.DataFrame(data, columns=['Longitude', 'Latitude', 'Value'])

# Optionally, you can set longitude and latitude as index
df.set_index(['Longitude', 'Latitude'], inplace=True)

# Now, df contains your data as a DataFrame
print(df.head())

                           Value
Longitude Latitude
0         0         1.569454e-43
          1         9.999000e+03
          2         9.999000e+03
          3         9.999000e+03
          4         9.999000e+03

In [54]:
import struct
import pandas as pd
import numpy as np

# Replace binary_data with your actual binary data
# binary_data = b"..."  # Your binary data here

# Define the dimensions of your grid (e.g., 360 longitudes, 180 latitudes)
num_longitudes = 360
num_latitudes = 180

# Initialize an empty list to store the data
data = []

# Initialize an empty numpy array for the data
values = np.empty((num_latitudes, num_longitudes))

# Iterate over the binary data to unpack and organize it
for j in range(num_latitudes):
    for i in range(num_longitudes):
        # Calculate the starting position for each grid point in the binary data
        start_position = 4 * (i + num_longitudes * j)  # Assuming 4-byte (32-bit) float

        # Extract the floating-point value from the binary data
        value = struct.unpack('>f', binary_data[start_position : start_position + 4])[0]

        # Append the value to the data list
        data.append(value)

        # Store the value in the numpy array
        values[j, i] = value

# Create a Pandas DataFrame from the numpy array
df = pd.DataFrame(values, columns=range(num_longitudes))

# Set the longitude values as the index
df.index = range(num_latitudes)

# Replace 9999 values with NaN
df.replace(9999, np.nan, inplace=True)

In [55]:
df

,0,1,2,3,4,5,6,7,8,9,...,350,351,352,353,354,355,356,357,358,359
0,1.569454e-43,2.421444e-42,1.401298e-45,8.407791e-45,2.421444e-42,2.432654e-42,2.634441e-42,1.401158e-41,NaN,2.510621e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.394372,2.010396,-0.777441
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.987721e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.048872,0.576148,0.325336
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.432839e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.801488,-0.591850,-1.387647
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.259566e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.230570,-0.364693,0.146977
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.979464e-02,...,NaN,NaN,NaN,NaN,NaN,0.290505,0.190313,-0.235695,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,9.021742e-01,1.036410e+00,6.238809e-01,4.158753e-01,2.647388e-01,2.171936e-01,1.778351e-01,-8.655538e-02,0.056055,6.684712e-01,...,-1.195372e+00,-8.329581e-01,-5.989265e-01,-0.703458,-1.172731e+00,-1.668134,-1.910850,-1.399690,-0.961549,-0.741196
176,-9.422396e-01,-9.391465e-01,-1.016536e+00,-1.138305e+00,-1.127769e+00,-1.902392e+00,-2.083044e+00,-1.778394e+00,-1.000880,-5.408316e-01,...,-5.349812e-01,-5.000579e-01,-4.030022e-01,0.096740,-2.957639e-02,-0.112420,-0.263314,0.264358,-0.479113,-0.350007
177,-4.813825e-01,-3.538072e-01,-8.971719e-02,8.665294e-02,7.305778e-02,-8.208743e-02,3.260716e-02,-1.608406e-01,-0.006972,2.323340e-01,...,-6.329385e-01,-3.061016e-02,1.143510e-01,-0.295823,-7.545757e-01,-1.155299,-0.970522,-0.347039,-0.488809,-0.265899
178,-4.592853e-01,-8.771515e-01,-7.899441e-01,-4.081882e-01,-3.820059e-01,-7.936195e-01,-6.966103e-01,-9.583209e-01,-0.756997,-2.635876e-01,...,-1.210696e+00,-8.668677e-01,-8.044136e-01,-1.314772,-1.200976e+00,-0.751446,-0.728246,-0.820979,-0.605959,-0.786355
179,-8.998073e-01,-5.917488e-01,-7.242161e-01,-3.469379e-02,-2.784986e-01,-4.118112e-01,-3.242456e-01,-3.341162e-01,-0.248032,-2.138772e-01,...,9.816096e-42,6.305843e-42,7.567012e-42,0.000000,4.007714e-43,0.000000,NaN,NaN,NaN,NaN